<?php

namespace App;

use App\Mail\ProjectCreated;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        /*
        static::created(function ($project){
            \Mail::to($project->owner->email)->send(
                new ProjectCreated($project)
            );
        });
        */

    }

    public function tasks(){
        return $this->hasMany(Task::class)->orderByDesc('id');
    }

    public function owner(){
        return $this->belongsTo(User::class);
    }

    public function addTask($body){
        $this->tasks()->create(['body'=>$body]);
    }
}
